### ISSUE TITLE
Sentient pong paddles trying to kill me

### ISSUE THREAD

**Issue by ZanaDev** [RblSb/Pong2#1]
One moment I'm trying to learn some basic Kha stuff and the next I have to fend off an onslaught of random crap with cool music

Surprisingly fun game, nice work

**Comment by RblSb** [comment]
Thanks! Unfortunately, I had a development time limit, so the code is pretty untidy and can be difficult to understand. I would recommend check out https://github.com/RblSb/KhaHotReload repo for more simple dev experience with Kha and maybe https://github.com/RblSb/khaguide for api basics tutorial. Also you can ask questions in [Kha irc](http://forum.kode.tech/topic/6/irc-channel-kha-at-ktxsoftware-com) or Kha discord room on [Haxe server](https://discord.gg/vpKrQdc).

**Comment by RblSb** [comment]
Fusion is so good, but i think i like Zero Mission even more for epilogue.
